import { jsPDF } from 'jspdf';
import JSZip from 'jszip';
import { AppState, Chapter, Novel } from '../types';

/**
 * Export novel or chapter to clean formatted PDF
 */
export async function exportToPdf(novel: Novel, chapters: Chapter[], singleChapterId?: string) {
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'mm',
    format: 'a4',
  });

  const targetChapters = singleChapterId
    ? chapters.filter((c) => c.id === singleChapterId)
    : [...chapters].sort((a, b) => a.order - b.order);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Title Cover Page
  doc.setFillColor(250, 250, 250);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(17, 24, 39);
  
  // Split title if long
  const titleLines = doc.splitTextToSize(novel.title, contentWidth);
  doc.text(titleLines, margin, 70);

  if (novel.subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.setTextColor(107, 114, 128);
    doc.text(novel.subtitle, margin, 70 + titleLines.length * 10 + 5);
  }

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(14);
  doc.setTextColor(79, 70, 229);
  doc.text(`By ${novel.author}`, margin, pageHeight - 50);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(156, 163, 175);
  doc.text(`Generated by Natasha Novel Studio by Lunarica • ${new Date().toLocaleDateString()}`, margin, pageHeight - 30);

  // Chapter Pages
  targetChapters.forEach((chap) => {
    doc.addPage();
    let currentY = 30;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(17, 24, 39);
    doc.text(chap.title, margin, currentY);
    currentY += 12;

    doc.setDrawColor(229, 231, 235);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    currentY += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(55, 65, 81);

    // Paragraphs
    const paragraphs = chap.content.split('\n\n');
    paragraphs.forEach((p) => {
      if (!p.trim()) return;
      const lines = doc.splitTextToSize(p.trim(), contentWidth);
      const lineHeight = 6;
      const blockHeight = lines.length * lineHeight + 4;

      if (currentY + blockHeight > pageHeight - margin) {
        doc.addPage();
        currentY = 25;
      }

      doc.text(lines, margin, currentY);
      currentY += blockHeight;
    });
  });

  doc.save(`${novel.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_natasha.pdf`);
}

/**
 * Export novel to valid EPUB file structure using JSZip
 */
export async function exportToEpub(novel: Novel, chapters: Chapter[]) {
  const zip = new JSZip();
  const sortedChapters = [...chapters].sort((a, b) => a.order - b.order);
  const titleSlug = novel.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();

  // 1. mimetype
  zip.file('mimetype', 'application/epub+zip', { compression: 'STORE' });

  // 2. META-INF/container.xml
  zip.file(
    'META-INF/container.xml',
    `<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`
  );

  // 3. OEBPS/content.opf
  const manifestItems = sortedChapters
    .map((c, i) => `<item id="chapter_${i + 1}" href="chapter_${i + 1}.xhtml" media-type="application/xhtml+xml"/>`)
    .join('\n    ');

  const spineItems = sortedChapters
    .map((_, i) => `<itemref idref="chapter_${i + 1}"/>`)
    .join('\n    ');

  const contentOpf = `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookId" version="2.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>${escapeXml(novel.title)}</dc:title>
    <dc:creator>${escapeXml(novel.author)}</dc:creator>
    <dc:language>id</dc:language>
    <dc:publisher>Natasha by Lunarica</dc:publisher>
    <dc:identifier id="BookId">urn:uuid:${novel.id}</dc:identifier>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    ${manifestItems}
  </manifest>
  <spine toc="ncx">
    ${spineItems}
  </spine>
</package>`;

  zip.file('OEBPS/content.opf', contentOpf);

  // 4. OEBPS/toc.ncx
  const navPoints = sortedChapters
    .map(
      (c, i) => `
    <navPoint id="navPoint-${i + 1}" playOrder="${i + 1}">
      <navLabel><text>${escapeXml(c.title)}</text></navLabel>
      <content src="chapter_${i + 1}.xhtml"/>
    </navPoint>`
    )
    .join('');

  const tocNcx = `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="urn:uuid:${novel.id}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle><text>${escapeXml(novel.title)}</text></docTitle>
  <navMap>
    ${navPoints}
  </navMap>
</ncx>`;

  zip.file('OEBPS/toc.ncx', tocNcx);

  // 5. OEBPS/chapter_X.xhtml files
  sortedChapters.forEach((c, i) => {
    const paragraphs = c.content
      .split('\n\n')
      .map((p) => `<p>${escapeXml(p.trim())}</p>`)
      .join('\n');

    const xhtml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>${escapeXml(c.title)}</title>
  <style type="text/css">
    body { font-family: sans-serif; line-height: 1.6; padding: 1em; }
    h1 { font-size: 1.5em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }
    p { text-indent: 1.5em; margin-bottom: 0.8em; }
  </style>
</head>
<body>
  <h1>${escapeXml(c.title)}</h1>
  ${paragraphs}
</body>
</html>`;

    zip.file(`OEBPS/chapter_${i + 1}.xhtml`, xhtml);
  });

  // Generate blob & trigger download
  const blob = await zip.generateAsync({ type: 'blob' });
  saveBlob(blob, `${titleSlug}_natasha.epub`);
}

/**
 * Export TXT or Markdown file
 */
export function exportToTxtOrMd(novel: Novel, chapters: Chapter[], format: 'txt' | 'md') {
  const sortedChapters = [...chapters].sort((a, b) => a.order - b.order);
  let content = '';

  if (format === 'md') {
    content += `# ${novel.title}\n`;
    if (novel.subtitle) content += `*${novel.subtitle}*\n`;
    content += `**Author:** ${novel.author}\n\n`;
    content += `## Synopsis\n${novel.longSynopsis || novel.shortSynopsis}\n\n---\n\n`;

    sortedChapters.forEach((c) => {
      content += `## ${c.title}\n\n${c.content}\n\n---\n\n`;
    });
  } else {
    content += `${novel.title.toUpperCase()}\n`;
    if (novel.subtitle) content += `${novel.subtitle}\n`;
    content += `By ${novel.author}\n\n`;
    content += `SYNOPSIS:\n${novel.longSynopsis || novel.shortSynopsis}\n\n` + '='.repeat(40) + '\n\n';

    sortedChapters.forEach((c) => {
      content += `${c.title}\n\n${c.content}\n\n` + '-'.repeat(30) + '\n\n';
    });
  }

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const ext = format === 'md' ? 'md' : 'txt';
  saveBlob(blob, `${novel.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.${ext}`);
}

/**
 * Backup full app state to JSON
 */
export function exportBackupJson(state: AppState) {
  const jsonStr = JSON.stringify(state, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  saveBlob(blob, `natasha_backup_${new Date().toISOString().split('T')[0]}.json`);
}

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
